apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: api-ssl-certs
  namespace: cert-manager
spec:
  secretName: api-ssl-certs
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "<wild-card-domain>"
  dnsNames:
  - "<wild-card-domain>"
