apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: ssl-certs
  namespace: cert-manager
spec:
  secretName: ssl-certs
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: *.apd-dev.thesurgincalnet.com
  dnsNames:
  - "*.apd-dev.thesurgincalnet.com"

