apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: api-ssl-certs-test
  namespace: cert-manager
spec:
  secretName: api-ssl-certs-test
  issuerRef:
    name: letsencrypt-test
    kind: ClusterIssuer
  commonName: "*.api-apd-afl.thesurgicalnet.com"
  dnsNames:
  - "*.api-apd-afl.thesurgicalnet.com"
